services:
  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://root:123@cluster0.9thcp.mongodb.net/
    volumes:
      - ./server:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

volumes:
  backend-data:
  frontend-data:
